# Generated by Django 4.0.1 on 2022-07-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='display',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='hardDisk',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sound',
        ),
        migrations.CreateModel(
            name='CustomComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=100, null=True)),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='part4.cpu')),
                ('display', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='part4.display')),
                ('hardDisk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='part4.harddisk')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='part4.ram')),
                ('sound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='part4.sound')),
            ],
        ),
    ]
