# Generated by Django 4.0.1 on 2022-07-29 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('part4', '0002_remove_cart_cpu_remove_cart_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='part4.computer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customcomputer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
