# Generated by Django 4.0.1 on 2022-07-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0003_cart_computer_cart_user_customcomputer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='custom',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='CustomComputer',
        ),
    ]
