# Generated by Django 4.0.1 on 2022-07-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0004_computer_custom_delete_customcomputer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Computer',
            new_name='computer',
        ),
    ]
