# Generated by Django 4.0.1 on 2022-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0005_rename_computer_cart_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
